---
title: "Tier 3 Functional Enrichment"
author: "Carlota Myhre de Gouveia"
date: "2026-02-21"
output:
  html_document:
    toc: true
    toc_float: true
---

## Setup and load required libraries
```{r packages, results='hide'}
library(dplyr)
library(tidyr)
library(stringr)
library(topGO)
library(readr)
library(ggplot2)
library(pheatmap)
library(DT)
```

## Load EggNOG transcript‑level annotation
```{r load_eggnog_anns}
eggnog <- read.delim(
  "results/annotation/eggnog/Trinity.emapper.annotations",
  comment.char = "#",
  header = FALSE,
  sep = "\t",
  stringsAsFactors = FALSE,
  quote = ""
)

colnames(eggnog) <- c(
  "query_name", "seed_ortholog", "evalue", "score", "eggNOG_OGs",
  "max_annot_lvl", "COG_category", "Description", "Preferred_name",
  "GOs", "EC", "KEGG_ko", "KEGG_Pathway", "KEGG_Module",
  "KEGG_Reaction", "KEGG_rclass", "BRITE", "KEGG_TC",
  "CAZy", "BiGG_Reaction", "PFAMs"
)

DT::datatable(
  head(eggnog, 10),
  options = list(pageLength = 5, scrollX = TRUE),
  caption = "Preview of EggNOG transcript-level annotations"
)
```






