---
title: "Model Comparison and Gene Extraction for Tier 2b"
author: "Carlota Myhre de Gouveia"
date: "2026-09-04"
output:
  html_document:
    toc: true
    toc_float: true
output_dir: "../docs/chapter1_rnaseq/DE_reports"
---
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(
  root.dir   = here::here(),
  output.dir = here::here("../docs/chapter1_rnaseq/DE_reports")
)
```

# Model comparison via likelihood ratio tests (LRTs)

## Setup and load required libraries
```{r packages, results='hide'}
## Setup and load required libraries
suppressPackageStartupMessages({
  library(DESeq2)
  library(tidyverse)
  library(dplyr)
  library(UpSetR)
  library(ggplot2)
  library(BiocParallel)
  library(limma)
  library(readxl)
  library(lme4)
})

library(reformulas)
library(variancePartition)


# Control settings for lmer
ctrl <- lmerControl(optimizer = "bobyqa", calc.derivs = FALSE)
```


## Data Import and Preprocessing
```{r load_data}
abundance_matrix <- read.table("data/DE/abundance_matrix.txt",
                               header = TRUE, row.names = 1, check.names = FALSE)
colnames(abundance_matrix) <- sub(".*Melops", "", colnames(abundance_matrix))

sample_info <- read_excel("data/sample_conditions_rnaseq.xlsx") %>%
  mutate(
    sample = sub("L", "", RNA_Later_ID),
    origin = factor(Origin, levels = c("W","H","S")),
    temperature = factor(`Temperature (celsius)`, levels = c(12,15,18)),
    condition = factor(RNAseqgroup,
                       levels = c("W12","W15","W18",
                                  "H12","H15","H18",
                                  "S12","S15","S18")),
    length = scale(`Total length (mm)`)  
  ) %>%
  select(sample, origin, temperature, condition, length) %>%
  arrange(match(sample, colnames(abundance_matrix)))

sample_info <- as.data.frame(sample_info)
rownames(sample_info) <- sample_info$sample
```

## Prepare abundance matrix
```{r prep_abundance_matrix}

# Ensure non-negative integer count
abundance_matrix <- round(pmax(abundance_matrix, 0))  

# Keep transcripts with total count ≥ 10 across all samples
keep_genes <- rowSums(abundance_matrix) >= 10
abundance_matrix <- abundance_matrix[keep_genes, ]
```



